language: ruby

rvm:
  - 2.0.0
  - 2.1.3
  - 2.1.7
  - 2.2.3

env:
  - LOGIN_URL=https://dev.login.library.nyu.edu SSO_LOGOUT_PATH=/logout

before_script:
  - mysql -e 'create database marli_test;'
  - bundle exec rake db:schema:load
  - bundle exec rake db:fixtures:load
  - bundle exec rake tmp:cache:clear

script:
  - RAILS_ENV=test bundle exec rspec
  - RAILS_ENV=test bundle exec cucumber

bundler_args: --without development

env:
  - PRIVILEGES_BASE_URL=https://localhost PRIVILEGES_SUBLIBRARY_CODE=marli

notifications:
  email:
    - lib-webservices@nyu.edu

sudo: false
