language: ruby

before_script:
  - mysql -e 'create database nyu_marli_test;'
  - bundle exec rake db:schema:load RAILS_ENV=test

rvm:
  - "1.9.3"
  - "1.9.2"

git:
  submodules: false

notifications:
  email:
    - barnaby.alter@nyu.edu
