version: "3"
services:
  app:
    build: .
    # volumes:
    #   - .:/app
    ports:
      - "3000:3000"
    env_file:
      - test.env
    environment:
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    depends_on:
      - setup_dbs

  test:
    # volumes:
    #   - .:/app
    tty: true
    stdin_open: true
    build: .
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: "tail -f /dev/null"
    depends_on:
      - setup_dbs

  setup_dbs:
    build: .
    environment:
      MARLI_DB_HOST: db
      RAILS_ENV: test
    command: bash -c "sleep 5; rake db:setup"
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
