version: '3.7'

x-build_default: &build_default
  image: marli
  build:
    context: .
    cache_from:
      - ruby:2.6-alpine
      - marli
      - quay.io/nyulibraries/marli:${BRANCH_NO_SLASH}
      - quay.io/nyulibraries/marli:latest
    args:
      BUNDLE_WITHOUT: "no_docker development test"

x-build_test: &build_test
  image: marli_test
  build:
    context: .
    dockerfile: Dockerfile.test
    cache_from:
      - ruby:2.6-slim
      - marli_test
      - quay.io/nyulibraries/marli_test:${BRANCH_NO_SLASH}
      - quay.io/nyulibraries/marli_test:latest

services:
  dev-server:
    <<: *build_default
    ports:
      - "9292:9292"
    env_file:
      - test.env
    command: ["./script/start.sh", "development"]
    depends_on:
      - setup_dbs
    volumes:
      - ./:/app

  test-server:
    <<: *build_test
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    # command: ["bundle", "exec", "rake"]
    depends_on:
      - setup_test_dbs
      - chrome
    ports:
      - "3000:3000"
  
  run-tests:  
    <<: *build_test
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    env_file:
      - test.env
    command: ["bundle", "exec", "rake"]
    depends_on:
      - test-server

  setup_test_dbs:
    <<: *build_test
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  setup_dbs:
    <<: *build_test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  chrome:
    image: selenium/standalone-chrome:4.0
    shm_size: 2g
    environment:
      - START_XVFB=false
    ports:
      - 7900:7900
      - 4444:4444