version: "3"
services:
  dev:
    build: .
    volumes:
      - ./app:/app/app
      - ./vendor:/app/vendor
      - bundle_cache:/bundle
    ports:
      - "3000:3000"
    env_file:
      - test.env
    environment:
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    depends_on:
      - setup_dbs

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - bundle_cache:/bundle
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake"]
    depends_on:
      - setup_dbs

  setup_test_dbs:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - bundle_cache:/bundle
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  setup_dbs:
    build: .
    volumes:
      - bundle_cache:/bundle
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

volumes:
  bundle_cache:
