version: '3.7'
x-build: &build
  build:
    context: .
    cache_from:
      - marli
      - quay.io/nyulibraries/marli
      - quay.io/nyulibraries/marli:$BRANCH_NO_SLASH
  image: marli
  tty: true
  stdin_open: true
x-test-env: &test-env
  <<: *build
  environment:
    RAILS_ENV: test
    MARLI_DB_DATABASE: rooms_test
    BRANCH_NO_SLASH:
    CI:
    CODECLIMATE_REPO_TOKEN:
    COVERALLS_REPO_TOKEN:
  env_file:
    - test.env
x-dev-env: &dev-env
  <<: *build
  env_file:
    - test.env

services:
  dev:
    <<: *dev-env
    ports:
      - "3000:3000"
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    depends_on:
      - setup_dbs
    volumes:
      - ./app:/app/app
      - ./vendor:/app/vendor
      - bundle_cache:/bundle

  test:
    <<: *test-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake"]
    depends_on:
      - setup_test_dbs
    volumes:
      - bundle_cache:/bundle
      # - ./:/app

  setup_test_dbs:
    <<: *test-env
    volumes:
      - bundle_cache:/bundle
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  setup_dbs:
    <<: *dev-env
    volumes:
      - bundle_cache:/bundle
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

volumes:
  bundle_cache:
