version: '3.7'
x-build-image: &build-image
  build:
    context: .
    cache_from:
      - marli
      - quay.io/nyulibraries/marli
      - quay.io/nyulibraries/marli:$BRANCH_NO_SLASH
    args:
      BUNDLE_WITHOUT: "no_docker development test"
  environment:
    BRANCH_NO_SLASH:

services:
  marli_1:
    <<: *build-image
    image: marli
  marli_2:
    <<: *build-image
    image: "quay.io/nyulibraries/marli:latest"
    depends_on:
      - marli_1
  marli_3:
    <<: *build-image
    image: "quay.io/nyulibraries/marli:${BRANCH_NO_SLASH}"
    depends_on:
      - marli_2
  marli_4:
    <<: *build-image
    image: "quay.io/nyulibraries/marli:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}"
    depends_on:
      - marli_3
