web:
  build: .
  volumes:
    - .:/marli
  links:
    - db
  ports:
    - "3001:3000"
  environment:
    MARLI_DB_HOST: db
    PRIVILEGES_BASE_URL: https://privileges.library.nyu.edu
    PRIVILEGES_SUBLIBRARY_CODE: nyu_ag_noaleph_MaRLI
    LOGIN_URL: https://dev.login.library.nyu.edu
    SSO_LOGOUT_PATH: /logout
db:
  image: library/mysql:5.6.22
  expose:
    - "3306"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
