version: '3.7'

x-build_default: &build_default
  image: marli
  build:
    context: .
    cache_from:
      - ruby:2.6-alpine
      - marli
      - quay.io/nyulibraries/marli:${BRANCH_NO_SLASH}
      - quay.io/nyulibraries/marli:latest

x-build_test: &build_test
  image: marli_test
  build:
    context: .
    dockerfile: Dockerfile.test
    cache_from:
      - quay.io/nyulibraries/selenium_chrome_headless_ruby:2.6-slim-chrome_73
      - marli_test
      - quay.io/nyulibraries/marli_test:${BRANCH_NO_SLASH}
      - quay.io/nyulibraries/marli_test:latest

services:
  dev:
    <<: *build_default
    ports:
      - "9292:9292"
    env_file:
      - test.env
    command: ["./script/start.sh", "development"]
    depends_on:
      - setup_dbs

  test:
    <<: *build_test
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    env_file:
      - test.env
    command: ["bundle", "exec", "rake"]
    depends_on:
      - setup_test_dbs
  
  bundle:
    <<: *build_test

  setup_test_dbs:
    <<: *build_test
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  setup_dbs:
    <<: *build_test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
