web:
  extends:
    file: docker-compose.yml
    service: web
  links:
    - db
  environment:
    MARLI_DB_HOST: db
    PRIVILEGES_BASE_URL: https://privileges.library.nyu.edu
    PRIVILEGES_SUBLIBRARY_CODE: nyu_ag_noaleph_MaRLI
    LOGIN_URL: https://dev.login.library.nyu.edu
    SSO_LOGOUT_PATH: /logout
    RAILS_ENV: test
db:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
