docker-defaults: &docker-defaults
  docker:
    - image: cimg/base:2021.07
      environment:
        - IMAGE_NAME=marli
        - HERMES_DEPLOYMENT=marli-unicorn
  working_directory: ~/app
      
version: 2.1
commands:
  build_docker: 
    steps:
      - run:
          name: Build Docker
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose build
            docker-compose -f docker-compose.build.yml build
  test:
    steps:
      - run:
          name: Run tests
          command: |
            docker-compose run test
  docker_pull:
    steps:
      - run:
          name: Pull docker images
          command: |
            ./script/pull_docker.sh
  docker_push:
    steps:
      - run:
          name: Pull docker images
          command: |
            ./script/push_docker.sh
orbs:
  deploy: nyulibraries/deploy@0.0.7
jobs:
  hermes-deploy:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - deploy/hermes_setup:
          host: ${HERMES_HOST}
          secret: ${HERMES_SECRET}
          tag: ${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
          deployment: ${HERMES_DEPLOYMENT}
      - deploy/docker_auth:
          username: ${QUAY_USERNAME}
          password: ${QUAY_PASSWORD}
      - deploy/hermes_set_image
      - deploy/hermes_rollout_status
          
  test-and-build-image:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - docker_pull
      - build_docker
      - test
      - deploy/docker_auth:
          username: ${QUAY_USERNAME}
          password: ${QUAY_PASSWORD}
      - docker_push

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test-and-build-image
      - hermes-deploy:
          name: hermes-deploy-dev
          context: web-hermes-dev
          requires: 
            - test-and-build-image   
          filters:
            branches:
              ignore: master
      - hermes-deploy:
          name: hermes-deploy-prod
          context: web-hermes-prod
          requires: 
            - test-and-build-image   
          filters:
            branches:
              only: master   

