docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git-compose-1.22.0
  working_directory: ~/app

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      docker-compose build dev

version: 2
jobs:
  test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *build_docker
      - run:
          name: Run tests
          command: docker-compose run test

  deploy-dev:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - run:
          name: Deploy into staging via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/MaRLI/job/MaRLI%20Development%20Deploy/build/api

  deploy-prod:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - run:
          name: Deploy into production via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/MaRLI/job/MaRLI%20Production%20Deploy/build/api

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy-dev:
          requires:
              - test
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          requires:
              - test
          filters:
            branches:
              only: master
