docker-defaults: &docker-defaults
  docker:
    - image: cimg/base:2021.07
      environment:
        - IMAGE_NAME=marli
        - COMPOSE_PROJECT_NAME=marli
        - HERMES_DEPLOYMENT=marli-unicorn
        - HERMES_IMAGE_TAG=master
  working_directory: ~/app

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker-compose build
      docker-compose -f docker-compose.build.yml build

test: &test
  run:
    name: Test
    command: |
      docker-compose run test
      
pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker pull quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH} || docker pull quay.io/nyulibraries/${IMAGE_NAME}:latest
      docker pull quay.io/nyulibraries/${IMAGE_NAME}_test:${BRANCH_NO_SLASH} || docker pull quay.io/nyulibraries/${IMAGE_NAME}_test:latest

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker push quay.io/nyulibraries/${IMAGE_NAME}:latest
      docker push quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}
      docker push quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
      docker push quay.io/nyulibraries/${IMAGE_NAME}_test:latest
      docker push quay.io/nyulibraries/${IMAGE_NAME}_test:${BRANCH_NO_SLASH}
      docker push quay.io/nyulibraries/${IMAGE_NAME}_test:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

version: 2.1
orbs:
  hermes:
    executors:
      hermes:
        docker:
          - image: cimg/base:2021.07

    commands:
      export_env:
        parameters:
          client_tag:
            default: 'master'
            description: >
              Pick a specific hermesclient image tag, defaults to master
            type: string
          host:
            description: 'Point to the dev or prod hermes host'
            type: string
          secret:
            description: 'Supply the host secret'
            type: string
          tag:
            description: 'Image tag for deployment'
            type: string
          deployment:
            description: 'Kubernetes deployment name'
            type: string
          docker_host:
            default: 'quay.io'
            description: 'Provide docker host'
            type: string
          docker_username:
            description: 'Provide docker username'
            type: string
          docker_password: 
            description: 'Provide docker password'
            type: string
        steps:
          - run: 
              name: Export Hermes dev env vars
              command: |
                echo 'export HERMES_HOST=<<parameters.host>>' >> $BASH_ENV
                echo 'export HERMES_SECRET=<<parameters.secret>>' >> $BASH_ENV
                echo 'export TAG=<<parameters.tag>>' >> $BASH_ENV
                echo 'export HERMES_DEPLOYMENT=<<parameters.deployment>>' >> $BASH_ENV
      auth:
        steps:
          - run:
              name: Authenticate Docker 
              command: |
                docker login -u "<<parameters.docker_username>>" --password "<<parameters.docker_password>>" <<parameters.docker_host>>
      set_image:
        steps:
          - run: 
              name: "Set new image"
              command: |
                # export TAG=${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
                docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:<<parameters.client_tag>> setImage -deployment=$HERMES_DEPLOYMENT -tag=$TAG
      rollout_status:
        steps:
          - run: 
              name: "Get rollout status"
              command: |
                docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:<<parameters.client_tag>> rolloutStatus -deployment=$HERMES_DEPLOYMENT
    jobs:
      deploy:
        executor: hermes
        steps:
          - setup_remote_docker
          - export_env
          - set_image
          - rollout_status

jobs:
  hermes-deploy:
    docker:
      - image: quay.io/nyulibraries/hermesclient:master
        auth:
          username: ${QUAY_USERNAME}
          password: ${QUAY_PASSWORD}
        environment:
          - HERMES_DEPLOYMENT=${HERMES_DEPLOYMENT}
          - TAG=${CIRCLE_BRANCH//\//_}
          - HERMES_HOST=${HERMES_HOST}
          - HERMES_SECRET=${HERMES_SECRET}
    steps:
      - setup_remote_docker
      - run: |
          ./hermesclient setImage -deployment=$HERMES_DEPLOYMENT -tag=$TAG
      - run: |
          ./hermesclient rolloutStatus -deployment=$HERMES_DEPLOYMENT

  test-and-build-image:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *pull_docker
      # - <<: *build_docker
      # - <<: *test
      # - <<: *push_docker

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test-and-build-image
      - hermes-deploy:
          name: hermes-deploy-dev
          context: web-hermes-dev
          requires: 
            - test-and-build-image   
          filters:
            branches:
              ignore: master
      - hermes-deploy:
          name: hermes-deploy-prod
          context: web-hermes-prod
          requires: 
            - test-and-build-image   
          filters:
            branches:
              only: master   

