development: &development
  host: <%= Settings.databases.host %>
  database: <%= Settings.databases.database %>
  username: <%= Settings.databases.username %>
  password: <%= Settings.databases.password %>
  adapter: mysql2
  encoding: utf8
  socket: /tmp/mysql.sock

test: 
  adapter: mysql2
  encoding: utf8
  host: <%= Settings.databases.host %>
  database: <%= Settings.databases.database %>
  username: <%= Settings.databases.username %>
  password: <%= Settings.databases.password %>
  
staging:
  <<: *development
  host: <%= Settings.databases.host %>

production:  
  <<: *development
  host: <%= Settings.databases.host %>