databases:
  password: 
  username: root
  database: nyu_marli_test
  host: localhost
  
capistrano:
  server: 
  user: 
  path: 
  scm_username: 

newrelic:
  app_name: 'MaRLI'

login:
  default_admins: []
  pds_url: "https://login.library.nyu.edu"
  calling_system: "primo"
  login_url: "https://logindev.library.nyu.edu/pds?func=load-login&institute=NYU&calling_system=primo&url=https%3A%2F%2Fwebdev3.library.nyu.edu%2Fmarli%2Fvalidate%3Freturn_url%3Dhttps%253A%252F%252Fwebdev3.library.nyu.edu%252Fmarli%252F%26primo_action%3Dnew%26primo_controller%3Duser_sessions"
  
privileges:
  base_url: https://web1.library.nyu.edu/privileges_guide
  marli_code: nyu_ag_noaleph_MaRLI
  
emails:
  -
    institution: Dummy 1
    email: dummy@dummy.com
    
cookie: 
  domain: ".local"
  
secret_token: '9e42de4fc65ed2d82c28010cf9b774a2920f2cecb82f34946a191c97738c0680672d7014679b8c25056694907eb221892779683540453edbcb73d537dd9ac6d3'