databases:
  password: 
  username: root
  database: nyu_marli_test
  host: localhost
  
capistrano:
  server: 
  user: 
  path: 
  scm_username: 

newrelic:
  app_name: 'MaRLI'

login:
  default_admins: []
  pds_url: "https://login.university.nyu.edu"
  calling_system: "marli"
  redirect_logout_url: "https://login.university.edu/logout"
  
privileges:
  base_url: https://localhost/privileges_guide
  marli_code: marli
  
secret_token: '9e42de4fc65ed2d82c28010cf9b774a2920f2cecb82f34946a191c97738c0680672d7014679b8c25056694907eb221892779683540453edbcb73d537dd9ac6d3'

emails:
  -
    institution: Dummy 1
    email: dummy@university.edu
  -
    institution: Dummy 2
    email: dummy2@university.edu